# Generated by Django 5.2.17 on 2026-08-08 19:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_subject_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "college_name",
                    models.CharField(default="Navajyothi College", max_length=200),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="E-Navajyothi",
                        help_text="Shown in the sidebar and browser tab.",
                        max_length=60,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "affiliated_to",
                    models.CharField(
                        blank=True,
                        help_text="University the college is affiliated to.",
                        max_length=200,
                    ),
                ),
                ("principal_name", models.CharField(blank=True, max_length=120)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("district", models.CharField(blank=True, max_length=80)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Square works best. Shown in the sidebar and on printouts.",
                        null=True,
                        upload_to="branding/",
                    ),
                ),
                (
                    "brand_color",
                    models.CharField(
                        default="#0d6b7c",
                        help_text="Primary colour for navigation, buttons and links.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex colour such as #0d6b7c.",
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#b8802a",
                        help_text="Used sparingly for highlights.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex colour such as #0d6b7c.",
                            )
                        ],
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        choices=[
                            ("system", "Follow the device"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "attendance_threshold",
                    models.PositiveSmallIntegerField(
                        default=75,
                        help_text="Minimum attendance percentage a student must hold.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("max_internal_mark", models.PositiveSmallIntegerField(default=20)),
                ("max_exam_mark", models.PositiveSmallIntegerField(default=80)),
                (
                    "pass_percentage",
                    models.PositiveSmallIntegerField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Send SMS for notices. Needs Twilio credentials in .env.",
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Browser push notifications via Firebase.",
                    ),
                ),
                (
                    "notify_on_leave_decision",
                    models.BooleanField(
                        default=True,
                        help_text="Tell the applicant when leave is approved or rejected.",
                    ),
                ),
                (
                    "rows_per_page",
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "allow_student_profile_edit",
                    models.BooleanField(
                        default=True,
                        help_text="Let students change their own name, address and photo.",
                    ),
                ),
                ("allow_staff_profile_edit", models.BooleanField(default=True)),
                (
                    "footer_note",
                    models.CharField(
                        blank=True,
                        help_text="Appears at the bottom of every page.",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Batch selected by default on new forms and reports.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
