# Generated by Django 5.2.17 on 2026-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0034_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="fee_payment_url",
            field=models.URLField(
                blank=True,
                help_text="Shown as 'Pay Your Fee' on the sign-in page. Leave blank to hide the button.",
                verbose_name="Fee payment link",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="login_background",
            field=models.ImageField(
                blank=True,
                help_text="Photograph shown behind the sign-in card. A wide campus shot works well.",
                null=True,
                upload_to="branding/",
            ),
        ),
    ]
