# Generated by Django 5.2.17 on 2026-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0035_sitesettings_fee_payment_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="setup_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="aadhar_num",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_num",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="aadhar_num",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="phone_num",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="aadhar_num",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_num",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
