# Generated by Django 5.2.17 on 2026-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0037_mark_existing_installs_setup_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="college_name",
            field=models.CharField(default="Your College", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="short_name",
            field=models.CharField(
                default="SkillyCMS",
                help_text="Shown in the sidebar and browser tab.",
                max_length=60,
            ),
        ),
    ]
